apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-dep
  targetCPUUtilizationPercentage: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
