apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-env
spec:
  containers:
  - image: nginx
    name: nginx-pod
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: auth-secret
          key: admin
