apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hellos.testdevops.com
spec:
  group: testdevops.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                text:
                  type: string
                container_port:
                  type: integer
                  default: 80
                service_type:
                  type: string
                  default: "ClusterIP"
                service_port:
                  type: integer
                  default: 80
            status:
              type: object
              properties:
                phase:
                  type: string
  names:
    kind: Hello
    plural: hellos
  scope: Namespaced

