apiVersion: v1
kind: Pod
metadata:
  labels:
    run: host-path-pod
  name: host-path-pod
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: busybox
    name: host-path-pod
    volumeMounts:
    - name: host-path-vol
      mountPath: /host
  volumes:
  - name: host-path-vol
    hostPath:
      path: /

