apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  volumes:
  - name: empty-dir-vol
    emptyDir:
      sizeLimit: 1024Mi
  containers:
  - command:
    - sleep
    - infinity
    image: busybox
    name: busybox-container-1
    volumeMounts:
    - name: empty-dir-vol
      mountPath: /shared-folder
  - command:
    - sleep
    - infinity
    image: busybox
    name: busybox-container-2
    volumeMounts:
    - name: empty-dir-vol
      mountPath: /shared-folder
