apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-10mi
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: host-path
  hostPath:
    path: /mnt/data/10mi
