apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-pv-20mi
spec:
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: host-path
  hostPath:
    path: /mnt/data/20mi
