apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-3gb
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/2gb
