apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "infinity"]
    volumeMounts:
      - name: mydata
        mountPath: "/data"
  volumes:
  - name: mydata
    persistentVolumeClaim:
      claimName: local-path-pvc
