apiVersion: v1
kind: Pod
metadata:
  name: app-nodeaffinity-required
spec:
  containers:
    - image: nginx
      name: app
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: ["k3d-dev-agent-0"]
