apiVersion: v1
kind: Pod
metadata:
  name: app-pod-env
spec:
  containers:
  - name: app-container
    image: nginx
    env:
    - name: KEY_1
      valueFrom:
        configMapKeyRef:
          name: manifest-configmap
          key: key1
    - name: KEY_2
      valueFrom:
        configMapKeyRef:
          name: manifest-configmap
          key: key2
