apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"mydep","creationTimestamp":null,"labels":{"app":"mydep"}},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"mydep"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"mydep"}},"spec":{"containers":[{"name":"nginx","image":"nginx","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: null
  labels:
    app: mydep
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
