apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydep
  name: mysvc
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mydep
