apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-10-07T08:54:59Z"
  generation: 1
  labels:
    app: mydeploy
  name: mydeploy
  namespace: default
  resourceVersion: "373375"
  uid: 4862d1fa-d7a2-4f2b-b0d0-d9faca0555e4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mydeploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydeploy
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
